onos-config:
  openidc:
    issuer: https://dex.aetherproject.org/dex
#  image:
#    repository: smbaker/onos-config
#    tag: smbaker
#    pullPolicy: Always

#onos-topo:
#  image:
#    repository: smbaker/onos-topo
#    tag: smbaker
#    pullPolicy: Always

#onos-sdran-cli:
#  image:
#    repository: onosproject/onos-sdran-cli
#    tag: v0.7.0

#global:
#  storage:
#    controller: "atomix-controller.micro-onos.svc.cluster.local:5679"

import:
  sdcore-adapter:
    enabled: true

sdcore-adapter:
  prometheusEnabled: false
#  image:
#    repository: smbaker/sdcore-adapter
#    tag: smbaker
#    pullPolicy: Always
  # output: "/tmp/sdcore-adapter.out"
  # spgwEndpoint: "http://spgwc.omec:8080/v1/config"

onos-gui:
  ingress:
    enabled: false
  service:
    type: NodePort

aether-roc-gui:
  openidc:
        issuer: https://dex.aetherproject.org/dex
  ingress:
    enabled: false
  service:
    type: NodePort
  image:
     repository: smbaker/aether-roc-gui
     tag: smbaker
     pullPolicy: Always

aether-roc-api:
   image:
     repository: smbaker/aether-roc-api
     tag: smbaker
     pullPolicy: Always
#     tag: v0.6.18
   corsOrigins:
   - https://editor.swagger.io
